### PR TITLE
Fix layouts not being taken in by plotvuer

### PR DESCRIPTION
**Pull request by Tehsurfer**

### CODE REVIEW

**Review by alan-wu — CHANGES_REQUESTED** [review]
135, 318, 320: The select ui in the input parameters interface is too wide, causing the scrollbar on the left.

157, 308, 318. 320: The zoom controls for simulation overlap with the plots.
The text input in the input parameters should be longer and the boundary should be purple when active.
The label of x-axis cannot be found.
There seems to be sizing issue with the plots when there are more than one.

**Comment by agarny** [comment]
Good job @Tehsurfer! A few things though:

- **Dataset 135:** if you change the `Simulation mode` from `Normal sinus rhythm` to `Stellate stimulation` then you can see a `Stimulation level` entry. For that entry, there is a slider and an input box. However, compared with [sparc.science](https://sparc.science/datasets/simulationviewer?id=135), that slider and input box have a different position and/or size (it's the same for the other datasets).
- **PlotVuer:**
  - if some simulation results are plotted and you zoom in/out at the browser level (i.e. `Ctrl`+`+`/`-`) then the simulation results will flash as a result of, it seems, of being replotted using two different X scales.
  - If you zoom a particular region (i.e. `Shift` + left mouse button) then, in [sparc.science](https://sparc.science/datasets/simulationviewer?id=135), the whole plot area is greyed out except for the region you want to zoom in. In the Vue 3 version, nothing is greyed out.

**Comment by Tehsurfer** [comment]
@agarny I went through and looked at each of the points you made above! I'd like to put the code in as is ideally, I'm not sure users will notice those changes, but if they do, I'm happy to work on them then. (This is because all those fixes require a deeper dive into plotly/element-ui workings than what I currently know about)

> Dataset 135: if you change the Simulation mode from Normal sinus rhythm to Stellate stimulation then you can see a Stimulation level .... that slider and input box have a different position and/or size (it's the same for the other datasets).


They don't look that different to me! Anything in particular you want changed? 

Element ui has changed the size properties for their elements, so they won't look exactly the same unless I put a good bit of time into it

Old 
image

New
image


> PlotVuer:
if some simulation results are plotted and you zoom in/out at the browser level (i.e. Ctrl++/-) then the simulation results will flash as a result of, it seems, of being replotted using two different X scales.

We have to replot the plots on resizing, if you have any ideas on what to do though let me know.

Not sure I understand this one though, maybe you can send me a video on slack or show me in the office



> If you zoom a particular region (i.e. Shift + left mouse button) then, in [sparc.science](https://sparc.science/datasets/simulationviewer?id=135), the whole plot area is greyed out except for the region you want to zoom in. In the Vue 3 version, nothing is greyed out.


Mmm yeah you're right, no idea how to fix that. I'd like to wait to work on that one until a non-developer points out it is an issue. Otherwise, if you like, I can disable that feature

**Comment by agarny** [comment]
> They don't look that different to me! Anything in particular you want changed?

I want them to look the same. I also spent time, back then, on getting things "right" and it doesn't look "right" to me anymore.

But, I leave it to you guys to decide whether to spend more time on it or not. If you don't then it's fine, I will try to have a look at it at some point since it does bother me indeed.

> We have to replot the plots on resizing, if you have any ideas on what to do though let me know.

Sure, whatever needs to be done. It's just that on sparc.science, you don't see that flashing while you do in the Vue3 version.

> Not sure I understand this one though, maybe you can send me a video on slack or show me in the office

I just mean zooming in/out the web page using `Ctrl`+`+`/`-`. See below (left: Vue3 version; right: sparc.science):

https://github.com/ABI-Software/simulationvuer/assets/602265/f31256ae-bc60-4e49-9557-4c42cfc2c339

> Mmm yeah you're right, no idea how to fix that. I'd like to wait to work on that one until a non-developer points out it is an issue. Otherwise, if you like, I can disable that feature

My feedback wasn't from a developer viewpoint but from an end-user viewpoint. For me, that's a regression, but again I leave it to you guys to decide.

**Comment by alan-wu** [comment]
This ti

> > They don't look that different to me! Anything in particular you want changed?
> 
> I want them to look the same. I also spent time, back then, on getting things "right" and it doesn't look "right" to me anymore.
> 
> But, I leave it to you guys to decide whether to spend more time on it or not. If you don't then it's fine, I will try to have a look at it at some point since it does bother me indeed.
> 
> > We have to replot the plots on resizing, if you have any ideas on what to do though let me know.
> 
> Sure, whatever needs to be done. It's just that on sparc.science, you don't see that flashing while you do in the Vue3 version.
> 
> > Not sure I understand this one though, maybe you can send me a video on slack or show me in the office
> 
> I just mean zooming in/out the web page using `Ctrl`+`+`/`-`. See below (left: Vue3 version; right: sparc.science):
> Untitled.mp4
> 
> > Mmm yeah you're right, no idea how to fix that. I'd like to wait to work on that one until a non-developer points out it is an issue. Otherwise, if you like, I can disable that feature
> 
> My feedback wasn't from a developer viewpoint but from an end-user viewpoint. For me, that's a regression, but again I leave it to you guys to decide.

This UI has been improved with the changes in this pull request, I will merge this one in for now and hopefully one of us will have the time to revisit this in the next couple of weeks.

**Pull request merged**
