### PR TITLE
Move to Vue 3, Switch to using the new version of plotvuer

### PR DESCRIPTION
**Pull request by Tehsurfer**
Use 
`npm install @abi-software/simulationvuer@alpha`
to test

image (15)

### CODE REVIEW

**Comment by Tehsurfer** [comment]
Currently stuck with this error:

image


I've tried to remove all the references to element-ui but the seem to always come back :(

**Comment by Tehsurfer** [comment]
Now working :)

**Review by alan-wu — CHANGES_REQUESTED** [review]
Entry is needed for the export, for example: 

With vite - export should be stated in the package.json file now - similar to the following:

```
  "type": "module",
  "main": "./dist/scaffoldvuer.umd.cjs",
  "module": "./dist/scaffoldvuer.js",
  "exports": {
    ".": {
      "import": "./dist/scaffoldvuer.js",
      "require": "./dist/scaffoldvuer.umd.cjs"
    },
    "./dist/style.css": "./dist/style.css",
    "./src/*": "./src/*"
  },
```

**Review by alan-wu — APPROVED** [review]
Looks good to me.

**Pull request merged**
